### ISSUE TITLE
Multi User

### ISSUE THREAD

**Issue by supportreq** [girish17/op-mattermost#25]
Does the plugin work for multiple users where each openproject user is a mattermost user?

How to map the two user ids?

**Comment by girish17** [comment]
Firstly, this is not a plugin. It is a [slash command](https://developers.mattermost.com/integrate/slash-commands/) integration. The decision to build a slash command and not a plugin was made based on this [Mattermost article](https://developers.mattermost.com/integrate/getting-started/how-should-i-integrate/). The plugin development for the same is a [separate project](https://github.com/girish17/op-mattermost-plugin) and still under progress and not ready for publishing.

Secondly, multiple users can use this OpenProject slash command. The configuration needs to be done on a per user basis. Every user will have their own version of this integration running on their own device. The advantage of this is that it provides more freedom and control to the Mattermost user (who is also an OpenProject user) .

Lastly, there is no mapping of two user ids.  However, there is mapping of tokens generated for a user from Mattermost and OpenProject accounts stored in a `.env` file as described [here](https://github.com/girish17/op-mattermost#setup)

**Comment by girish17** [comment]
@supportreq Please try out this new OpenProject [plugin](https://github.com/girish17/op-mm-plugin) for Mattermost. It achieves the feature you asked for.  
The installable is available [here](https://github.com/girish17/op-mm-plugin/releases/tag/v0.2.2)
